apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-spring-app.secretName" . }}
  labels:
    {{- include "simple-spring-app.labels" . | nindent 4 }}
type: Opaque

data:
  postgresUser: {{ .Values.app.postgres.username | b64enc | quote }}
  postgresPassword: {{ randAlphaNum 12 | b64enc | quote }}
  postgresAdminPassword: {{ randAlphaNum 12 | b64enc | quote }}
