name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        default: 'kindest/node:v1.29.2'
        required: false
        type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: ${{ github.event.inputs.node_image }}

      - name: Build image
        uses: docker/build-push-action@v5
        if: steps.list-changed.outputs.changed == 'true'
        with:
          context: .
          push: true
          tags: kind-registry:5000/simple-spring-app:testing

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --charts charts/simple-spring-app --helm-extra-set-args "--set=image.tag=testing --set=image.repository=kind-registry:5000/simple-spring-app"
