name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        default: 'kindest/node:v1.29.2'
        required: false
        type: string

jobs:
  lint-test:
    env:
      REGISTRY: kind-registry:5000
      IMAGE_NAME: simple-spring-app
      IMAGE_TAG: testing
      CHART_DIR: charts/simple-spring-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.29.2' }}
          version: v0.20.0

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./simple-spring-app/
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Run chart-testing (install)
        run: |
          ct install --charts ${{ env.CHART_DIR }} --helm-extra-set-args "--set=image.tag=${{ env.IMAGE_TAG }} --set=image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
